project_id = "icwpvjixmmcwarexyagk"

[functions.auto-send-messages]
verify_jwt = false

[functions.test-send-message]
verify_jwt = false

[functions.chatbot-webhook]
verify_jwt = false

[functions.manage-instance]
verify_jwt = false